<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="uft-8"/>
        <title>Code Sharing Platform</title>
        <script type="text/javascript" src="/js/send.js"></script>
        <link href="/css/style.css" rel="stylesheet">
    </head>
    <body>
        <form>
            <textarea id="code_snippet_textarea" required placeholder="//write your code here"></textarea>
            <br/>
            <button id="send_snippet" type="submit" onclick="send()">Submit</button>
        </form>
    </body>
</html>